export const TOP_COMPANIES = [
  "Google",
  "Microsoft",
  "Amazon",
  "Apple",
  "Meta",
  "Tesla",
  "Netflix",
  "Stripe",
  "Uber",
  "Airbnb",
  "LinkedIn",
  "Spotify",
  "Twitter",
  "Dropbox",
  "Slack",
  "Figma",
  "Notion",
  "GitHub",
  "GitLab",
  "Atlassian",
  "JetBrains",
  "MongoDB",
  "Redis",
  "Twilio",
  "SendGrid",
  "Vercel",
  "Netlify",
  "Heroku",
  "AWS",
  "Salesforce",
];

export const TOP_ROLES_BY_GROUP = [
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Engineer",
  "Principal Engineer",
  "Backend Engineer",
  "Frontend Engineer",
  "Full Stack Engineer",
  "DevOps Engineer",
  "Data Engineer",
  "Machine Learning Engineer",
  "Product Manager",
  "Technical Lead",
  "Engineering Manager",
  "Solutions Architect",
  "Systems Engineer",
];
