TOP_COMPANIES = [
    "TCS",
    "Infosys",
    "Wipro",
    "HCL Technologies",
    "Tech Mahindra",
    "Google India",
    "Microsoft India",
    "Amazon India",
    "Flipkart",
    "Paytm",
    "Zomato",
    "Swiggy",
    "BYJU'S",
    "Ola",
    "PhonePe",
]

TOP_ROLES_BY_GROUP = {
    "Engineering": [
        "Software Engineer / SDE",
        "Staff Engineer",
        "Full Stack Developer",
        "Backend Developer",
        "Frontend Developer",
        "DevOps Engineer",
        "QA Engineer / SDET",
        "Mobile App Developer",
        "Machine Learning Engineer",
        "Cloud Engineer",
        "Technical Lead",
    ],
    "Data & AI": ["Data Scientist", "Data Analyst"],
    "Product & Business": ["Product Manager", "Business Analyst"],
}
